### ISSUE TITLE
Example: User Log-In

### ISSUE THREAD

**Issue by mmc-de** [ciis-uoc/repository-template#1]
## Description

As a user, I want to be able to log-in to the system to access my personal information.

## Acceptance Criteria

- The user is logged in if the entered e-mail matches the entered password
- The system informs the user if the login succeeds / fails

## Tasks

- [ ] Build log-in form
- [ ] Implement back-end function to check input
- [ ] Test with correct and incorrect inputs
