### ISSUE TITLE
Example: Change Password

### ISSUE THREAD

**Issue by mmc-de** [ciis-uoc/repository-template#2]
## Description

As a user, I want to be able to change password to stay secure and (re-)access my account.

## Acceptance Criteria

- The systems sents the user a e-mail with the possibility to reset the password
- When the user visits the link in the e-mail, he can choose a new password
- The password is changed and the user is forwarded to the login page of the website

## Tasks

- [ ] Add button to reset password
- [ ] Implement "reset password" form
- [ ] Build backend function
